services:
  db:
    image: mongo:7
    container_name: Handoff_mongoDB
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "try { rs.status().ok } catch(e) { rs.initiate().ok }", "--quiet"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-data: